version: '3.8'

services:
  db:
    image: 'postgres:latest'
    container_name: tender-db
    environment:
      POSTGRES_DB: tender
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - '7432:5432'
#    volumes:
#      - postgres-data:/var/lib/postgresql/data