spring:
  application:
    name: tender-service
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:7432/tender
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

server:
  port: 8081

logging:
  level:
    sql: debug
    com.tenderservice: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    com:
      zaxxer:
        hikari: debug

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operations-sorter: 'alpha'
    tags-sorter: 'alpha'
